from datetime import date
from pathlib import Path
import yaml
import config
from config import VAULT_ROOT, CATEGORY_DIRS


def build_frontmatter(topic: dict, sources: list[dict], status: str, confidence: str, read_time: int) -> str:
    tags = [s.replace(" ", "-").lower() for s in topic.get("search_terms", [])]
    fm = {
        "title": topic["title"],
        "date": date.today().isoformat(),
        "category": topic["category"],
        "subcategory": topic["subcategory"],
        "tags": tags,
        "status": status,
        "confidence": confidence,
        "read_time_minutes": read_time,
        "sources": sources,
        "generated_by": config.CLAUDE_MODEL,
        "reviewed": False,
        "discussion_ready": True,
    }
    return "---\n" + yaml.dump(fm, allow_unicode=True, default_flow_style=False, sort_keys=False) + "---\n"


def build_note_body(topic: dict, synthesis: str, sources: list[dict]) -> str:
    lines = [f"# {topic['title']}\n", synthesis, "\n"]
    if any(s["type"] == "wikipedia" for s in sources):
        wiki_src = next(s for s in sources if s["type"] == "wikipedia")
        lines.append(f"\n---\n*Wikipedia source: [{topic['title']}]({wiki_src['url']}) · Retrieved {wiki_src['retrieved']}*")
    arxiv_srcs = [s for s in sources if s["type"] == "arxiv"]
    if arxiv_srcs:
        lines.append("\n**Recent arXiv papers:**")
        for s in arxiv_srcs:
            lines.append(f"- [{s.get('title', s['id'])}](https://arxiv.org/abs/{s['id']}) ({s.get('year', '')})")
    return "\n".join(lines)


def write_topic_note(topic: dict, body: str) -> Path:
    cat_dir = CATEGORY_DIRS.get(topic["category"], VAULT_ROOT / "Topics" / topic["category"])
    cat_dir.mkdir(parents=True, exist_ok=True)
    note_path = cat_dir / f"{topic['id']}.md"
    note_path.write_text(body, encoding="utf-8")
    return note_path


def write_daily_note(run_date: date, topic_notes: list[dict]) -> Path:
    daily_dir = VAULT_ROOT / "Daily"
    daily_dir.mkdir(parents=True, exist_ok=True)
    note_path = daily_dir / f"{run_date.isoformat()}.md"

    lines = [
        f"# Daily Knowledge Digest — {run_date.strftime('%B %d, %Y')}\n",
        f"**Topics covered today:** {len(topic_notes)}\n",
        "| Topic | Category | Status | Read Time | Note |\n",
        "|-------|----------|--------|-----------|------|\n",
    ]
    for tn in topic_notes:
        category = tn["topic"]["category"]
        subcategory = tn["topic"]["subcategory"]
        topic_id = tn["topic"]["id"]
        title = tn["topic"]["title"]
        status = tn.get("status", "unknown")
        read_time = tn.get("read_time", "?")
        wikilink = f"[[{topic_id}]]"
        lines.append(f"| {title} | {category} / {subcategory} | {status} | ~{read_time} min | {wikilink} |\n")

    lines.append("\n---\n")
    lines.append("## Discussion\n")
    lines.append("*Use this space for notes after reading. Open any topic note and use the Discussion Prompts inside.*\n")
    lines.append("\n---\n")
    lines.append(f"*Generated by daily_research.py at {run_date.isoformat()}*\n")

    note_path.write_text("".join(lines), encoding="utf-8")
    return note_path
